### ISSUE TITLE
Filtering by fields of relations

### ISSUE THREAD

**Issue by rimas-kudelis** [artprima/query-filter-bundle#5]
Is filtering by relation properties possible? If yes, what is the syntax? If not, do you think it would be difficult to implement?

**Comment by denisvmedia** [comment]
I'm not sure, what's the problem? Every field that can be used in doctrine's where can be used in QueryFilterBundle. Can you maybe describe the problem wider?

**Comment by rimas-kudelis** [comment]
What I meant is basically that it would be nice to have at least one example of filtering by a property of a related entity in the README.
If say I have `Post` Entities which have a many-to-many relationship to `Tag` entities, how do I filter posts by their tags?
Also, not exactly related, but: why do I need to prefix all fields in the filter with a `t.`?

**Comment by denisvmedia** [comment]
It's not a question for my bundle, it's a question on how you build your queries. For example:

```php
        $qb = $this->createQueryBuilder('c') // country
            ->leftJoin('c.branches', 'b')
            ->leftJoin('b.persons', 'p')
```

Here you can filter by the main entity `country` (alias `c`), by `c.branches` (alias `b`), by `b.persons` (alias `p`). Example url (I assume that you whitelisted the fields via `setSearchAllowedCols()` in your query config): http://127.0.0.1:8000/?filter[c.name]=Russia&filter[b.name]=Kremlin&filter[p.last_name]=Putin

This example also answers your question answers your last question: you don't need to prefix all the fields with `t.`, the prefix depends on the table alias used in your query builder.

You can also hide real field names at all by using `$config->setSearchByAliases()`. See [how it's done in the unit tests](https://github.com/artprima/query-filter-bundle/blob/d14db3cfbee526f0b5d56759c399e3023b048570/Tests/QueryFilter/QueryFilterTest.php#L204):

```php
        $config->setSearchAllowedCols(['fullname', 'c.heaven']);
        // ...
        $config->setSearchByAliases([
            (new Alias('fullname', 'concat(\'c.firstname, \' \', c.lastname\')'))
        ]);
```

Now you can use `fullname` instead of a compex query with concat. Of course, you can hide not just complex queries, but also simple fields, i.e.:

```php
        $config->setSearchAllowedCols(['user_firstname', 'c.heaven']);
        // ...
        $config->setSearchByAliases([
            (new Alias('user_firstname', 'c.firstname'))
        ]);
```
